export const GET_ADDRESSES_RESULT = 'GET_ADDRESSES_RESULT'
export const GET_INFO_RESULT = 'GET_INFO_RESULT'
export const GET_TRANSACTIONS_RESULT = 'GET_TRANSACTIONS_RESULT'
export const GET_SUPPORTS_RESULT = 'GET_SUPPORTS_RESULT'